# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(645, 903)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 621, 251))
        self.groupBox.setObjectName("groupBox")
        self.offset = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.offset.setGeometry(QtCore.QRect(320, 50, 101, 22))
        self.offset.setMaximum(10000.0)
        self.offset.setProperty("value", 100.0)
        self.offset.setObjectName("offset")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 20, 91, 21))
        self.label_4.setObjectName("label_4")
        self.psfSigmaX = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.psfSigmaX.setGeometry(QtCore.QRect(100, 110, 81, 22))
        self.psfSigmaX.setDecimals(3)
        self.psfSigmaX.setProperty("value", 2.0)
        self.psfSigmaX.setObjectName("psfSigmaX")
        self.gain = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.gain.setGeometry(QtCore.QRect(320, 20, 101, 22))
        self.gain.setDecimals(4)
        self.gain.setMaximum(1000.0)
        self.gain.setProperty("value", 1.0)
        self.gain.setObjectName("gain")
        self.roisize = QtWidgets.QSpinBox(self.groupBox)
        self.roisize.setGeometry(QtCore.QRect(120, 20, 111, 22))
        self.roisize.setProperty("value", 9)
        self.roisize.setObjectName("roisize")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(240, 50, 91, 21))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.label.setObjectName("label")
        self.detectionThreshold = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.detectionThreshold.setGeometry(QtCore.QRect(120, 50, 62, 22))
        self.detectionThreshold.setDecimals(4)
        self.detectionThreshold.setProperty("value", 5.0)
        self.detectionThreshold.setObjectName("detectionThreshold")
        self.btnBrowseTiff = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseTiff.setGeometry(QtCore.QRect(520, 140, 91, 23))
        self.btnBrowseTiff.setObjectName("btnBrowseTiff")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 140, 101, 21))
        self.label_7.setObjectName("label_7")
        self.tiffPath = QtWidgets.QLineEdit(self.groupBox)
        self.tiffPath.setGeometry(QtCore.QRect(120, 140, 391, 20))
        self.tiffPath.setObjectName("tiffPath")
        self.btnLocalize = QtWidgets.QPushButton(self.groupBox)
        self.btnLocalize.setGeometry(QtCore.QRect(10, 170, 141, 31))
        self.btnLocalize.setObjectName("btnLocalize")
        self.smlmLocsFile = QtWidgets.QLineEdit(self.groupBox)
        self.smlmLocsFile.setGeometry(QtCore.QRect(290, 170, 321, 21))
        self.smlmLocsFile.setObjectName("smlmLocsFile")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(160, 160, 131, 41))
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(240, 80, 91, 21))
        self.label_11.setObjectName("label_11")
        self.pixelsize = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.pixelsize.setGeometry(QtCore.QRect(320, 80, 101, 22))
        self.pixelsize.setMaximum(10000.0)
        self.pixelsize.setProperty("value", 100.0)
        self.pixelsize.setObjectName("pixelsize")
        self.labelLocsInfo = QtWidgets.QLabel(self.groupBox)
        self.labelLocsInfo.setGeometry(QtCore.QRect(160, 210, 451, 31))
        self.labelLocsInfo.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelLocsInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLocsInfo.setText("")
        self.labelLocsInfo.setObjectName("labelLocsInfo")
        self.btnLinkLocs = QtWidgets.QPushButton(self.groupBox)
        self.btnLinkLocs.setGeometry(QtCore.QRect(10, 210, 141, 31))
        self.btnLinkLocs.setObjectName("btnLinkLocs")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(430, 20, 131, 21))
        self.label_22.setObjectName("label_22")
        self.txtCameraOffsetFile = QtWidgets.QLineEdit(self.groupBox)
        self.txtCameraOffsetFile.setGeometry(QtCore.QRect(430, 50, 113, 20))
        self.txtCameraOffsetFile.setObjectName("txtCameraOffsetFile")
        self.btnBrowseCameraOffset = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseCameraOffset.setGeometry(QtCore.QRect(550, 50, 61, 23))
        self.btnBrowseCameraOffset.setObjectName("btnBrowseCameraOffset")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(20, 80, 91, 21))
        self.label_23.setObjectName("label_23")
        self.startFrame = QtWidgets.QSpinBox(self.groupBox)
        self.startFrame.setGeometry(QtCore.QRect(120, 80, 61, 22))
        self.startFrame.setSuffix("")
        self.startFrame.setMaximum(100000000)
        self.startFrame.setProperty("value", 0)
        self.startFrame.setObjectName("startFrame")
        self.checkEstimSigma = QtWidgets.QCheckBox(self.groupBox)
        self.checkEstimSigma.setGeometry(QtCore.QRect(290, 110, 151, 17))
        self.checkEstimSigma.setObjectName("checkEstimSigma")
        self.psfSigmaY = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.psfSigmaY.setGeometry(QtCore.QRect(190, 110, 81, 22))
        self.psfSigmaY.setDecimals(3)
        self.psfSigmaY.setProperty("value", 2.0)
        self.psfSigmaY.setObjectName("psfSigmaY")
        self.groupPatternEstim = QtWidgets.QGroupBox(Dialog)
        self.groupPatternEstim.setGeometry(QtCore.QRect(10, 400, 621, 351))
        self.groupPatternEstim.setObjectName("groupPatternEstim")
        self.label_2 = QtWidgets.QLabel(self.groupPatternEstim)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.label_2.setObjectName("label_2")
        self.numPhaseSteps = QtWidgets.QSpinBox(self.groupPatternEstim)
        self.numPhaseSteps.setGeometry(QtCore.QRect(140, 20, 61, 21))
        self.numPhaseSteps.setMinimum(2)
        self.numPhaseSteps.setObjectName("numPhaseSteps")
        self.btnEstimAnglePitch = QtWidgets.QPushButton(self.groupPatternEstim)
        self.btnEstimAnglePitch.setGeometry(QtCore.QRect(10, 60, 151, 23))
        self.btnEstimAnglePitch.setObjectName("btnEstimAnglePitch")
        self.minpitch = QtWidgets.QDoubleSpinBox(self.groupPatternEstim)
        self.minpitch.setGeometry(QtCore.QRect(300, 20, 62, 22))
        self.minpitch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.minpitch.setDecimals(4)
        self.minpitch.setProperty("value", 3.3)
        self.minpitch.setObjectName("minpitch")
        self.maxpitch = QtWidgets.QDoubleSpinBox(self.groupPatternEstim)
        self.maxpitch.setGeometry(QtCore.QRect(450, 20, 62, 22))
        self.maxpitch.setDecimals(4)
        self.maxpitch.setProperty("value", 3.5)
        self.maxpitch.setObjectName("maxpitch")
        self.label_9 = QtWidgets.QLabel(self.groupPatternEstim)
        self.label_9.setGeometry(QtCore.QRect(230, 20, 91, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupPatternEstim)
        self.label_10.setGeometry(QtCore.QRect(370, 20, 91, 21))
        self.label_10.setObjectName("label_10")
        self.btnEstimPhaseDepth = QtWidgets.QPushButton(self.groupPatternEstim)
        self.btnEstimPhaseDepth.setGeometry(QtCore.QRect(10, 130, 151, 21))
        self.btnEstimPhaseDepth.setObjectName("btnEstimPhaseDepth")
        self.angle1 = QtWidgets.QDoubleSpinBox(self.groupPatternEstim)
        self.angle1.setGeometry(QtCore.QRect(340, 60, 81, 22))
        self.angle1.setDecimals(4)
        self.angle1.setProperty("value", 0.0)
        self.angle1.setObjectName("angle1")
        self.angle0 = QtWidgets.QDoubleSpinBox(self.groupPatternEstim)
        self.angle0.setGeometry(QtCore.QRect(261, 60, 71, 22))
        self.angle0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.angle0.setDecimals(4)
        self.angle0.setProperty("value", 0.0)
        self.angle0.setObjectName("angle0")
        self.label_12 = QtWidgets.QLabel(self.groupPatternEstim)
        self.label_12.setGeometry(QtCore.QRect(180, 60, 81, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupPatternEstim)
        self.label_13.setGeometry(QtCore.QRect(180, 90, 71, 21))
        self.label_13.setObjectName("label_13")
        self.pitch1 = QtWidgets.QDoubleSpinBox(self.groupPatternEstim)
        self.pitch1.setGeometry(QtCore.QRect(340, 90, 81, 22))
        self.pitch1.setDecimals(4)
        self.pitch1.setMaximum(1000.0)
        self.pitch1.setProperty("value", 0.0)
        self.pitch1.setObjectName("pitch1")
        self.pitch0 = QtWidgets.QDoubleSpinBox(self.groupPatternEstim)
        self.pitch0.setGeometry(QtCore.QRect(261, 90, 71, 22))
        self.pitch0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pitch0.setDecimals(4)
        self.pitch0.setMaximum(1000.0)
        self.pitch0.setProperty("value", 0.0)
        self.pitch0.setObjectName("pitch0")
        self.fixDepth = QtWidgets.QDoubleSpinBox(self.groupPatternEstim)
        self.fixDepth.setGeometry(QtCore.QRect(90, 160, 62, 22))
        self.fixDepth.setMaximum(1.0)
        self.fixDepth.setProperty("value", 0.9)
        self.fixDepth.setObjectName("fixDepth")
        self.btnFixDepth = QtWidgets.QPushButton(self.groupPatternEstim)
        self.btnFixDepth.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.btnFixDepth.setObjectName("btnFixDepth")
        self.tableMod = QtWidgets.QTableWidget(self.groupPatternEstim)
        self.tableMod.setGeometry(QtCore.QRect(180, 120, 431, 221))
        self.tableMod.setObjectName("tableMod")
        self.tableMod.setColumnCount(0)
        self.tableMod.setRowCount(0)
        self.btnSaveMod = QtWidgets.QPushButton(self.groupPatternEstim)
        self.btnSaveMod.setGeometry(QtCore.QRect(10, 190, 161, 23))
        self.btnSaveMod.setObjectName("btnSaveMod")
        self.btnLoadMod = QtWidgets.QPushButton(self.groupPatternEstim)
        self.btnLoadMod.setGeometry(QtCore.QRect(10, 220, 161, 23))
        self.btnLoadMod.setObjectName("btnLoadMod")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 621, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnExtractROIs = QtWidgets.QPushButton(self.groupBox_2)
        self.btnExtractROIs.setGeometry(QtCore.QRect(10, 20, 171, 23))
        self.btnExtractROIs.setObjectName("btnExtractROIs")
        self.maxLinkFrameskip = QtWidgets.QSpinBox(self.groupBox_2)
        self.maxLinkFrameskip.setGeometry(QtCore.QRect(320, 40, 51, 22))
        self.maxLinkFrameskip.setProperty("value", 4)
        self.maxLinkFrameskip.setObjectName("maxLinkFrameskip")
        self.maxLinkDistance = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.maxLinkDistance.setGeometry(QtCore.QRect(320, 10, 51, 22))
        self.maxLinkDistance.setProperty("value", 0.5)
        self.maxLinkDistance.setObjectName("maxLinkDistance")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(190, 40, 111, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(190, 10, 131, 21))
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(190, 80, 101, 21))
        self.label_37.setObjectName("label_37")
        self.txtROIFile = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtROIFile.setGeometry(QtCore.QRect(310, 80, 191, 20))
        self.txtROIFile.setObjectName("txtROIFile")
        self.btnBrowseROIs = QtWidgets.QPushButton(self.groupBox_2)
        self.btnBrowseROIs.setGeometry(QtCore.QRect(510, 80, 91, 23))
        self.btnBrowseROIs.setObjectName("btnBrowseROIs")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(380, 10, 161, 21))
        self.label_36.setObjectName("label_36")
        self.maxLinkDistanceIntensity = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.maxLinkDistanceIntensity.setGeometry(QtCore.QRect(540, 10, 51, 22))
        self.maxLinkDistanceIntensity.setProperty("value", 0.5)
        self.maxLinkDistanceIntensity.setObjectName("maxLinkDistanceIntensity")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(380, 40, 151, 21))
        self.label_38.setObjectName("label_38")
        self.roiExtractAppend = QtWidgets.QSpinBox(self.groupBox_2)
        self.roiExtractAppend.setGeometry(QtCore.QRect(540, 40, 51, 22))
        self.roiExtractAppend.setProperty("value", 0)
        self.roiExtractAppend.setObjectName("roiExtractAppend")
        self.roiExtractSpotFrames = QtWidgets.QSpinBox(self.groupBox_2)
        self.roiExtractSpotFrames.setGeometry(QtCore.QRect(120, 50, 51, 22))
        self.roiExtractSpotFrames.setProperty("value", 20)
        self.roiExtractSpotFrames.setObjectName("roiExtractSpotFrames")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_40.setObjectName("label_40")
        self.roiExtractMinSpotFrames = QtWidgets.QSpinBox(self.groupBox_2)
        self.roiExtractMinSpotFrames.setGeometry(QtCore.QRect(120, 80, 51, 22))
        self.roiExtractMinSpotFrames.setProperty("value", 20)
        self.roiExtractMinSpotFrames.setObjectName("roiExtractMinSpotFrames")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 760, 621, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnRunSimflux = QtWidgets.QPushButton(self.groupBox_3)
        self.btnRunSimflux.setGeometry(QtCore.QRect(10, 20, 171, 31))
        self.btnRunSimflux.setObjectName("btnRunSimflux")
        self.btnDriftCorrection = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDriftCorrection.setGeometry(QtCore.QRect(10, 60, 171, 31))
        self.btnDriftCorrection.setObjectName("btnDriftCorrection")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SIMFLUX"))
        self.groupBox.setTitle(_translate("Dialog", "Spot detection and 2D Gaussian localization"))
        self.label_4.setText(_translate("Dialog", "Camera gain"))
        self.psfSigmaX.setSuffix(_translate("Dialog", " pixels"))
        self.roisize.setSuffix(_translate("Dialog", " pixels"))
        self.label_6.setText(_translate("Dialog", "Camera offset"))
        self.label_3.setText(_translate("Dialog", "ROI Size"))
        self.label_5.setText(_translate("Dialog", "PSF Sigma (X,Y):"))
        self.label.setText(_translate("Dialog", "Detection Threshold"))
        self.btnBrowseTiff.setText(_translate("Dialog", "Browse"))
        self.label_7.setText(_translate("Dialog", "TIFF Path"))
        self.btnLocalize.setText(_translate("Dialog", "2D Gaussian localization"))
        self.label_8.setText(_translate("Dialog", "2D Gaussian localizations:\n"
"(Picasso compatible)"))
        self.label_11.setText(_translate("Dialog", "Pixel size"))
        self.btnLinkLocs.setText(_translate("Dialog", "Measure on time"))
        self.label_22.setText(_translate("Dialog", "Use image based offset:"))
        self.btnBrowseCameraOffset.setText(_translate("Dialog", "Browse"))
        self.label_23.setText(_translate("Dialog", "Start frame"))
        self.checkEstimSigma.setText(_translate("Dialog", "Estimate PSF sigma"))
        self.psfSigmaY.setSuffix(_translate("Dialog", " pixels"))
        self.groupPatternEstim.setTitle(_translate("Dialog", "Pattern estimation"))
        self.label_2.setText(_translate("Dialog", "Number of phase steps"))
        self.btnEstimAnglePitch.setText(_translate("Dialog", "Estimate angles and pitch"))
        self.label_9.setText(_translate("Dialog", "Minimum pitch"))
        self.label_10.setText(_translate("Dialog", "Maximum pitch"))
        self.btnEstimPhaseDepth.setText(_translate("Dialog", "Estimate phase and depth"))
        self.label_12.setText(_translate("Dialog", "Angles (deg):"))
        self.label_13.setText(_translate("Dialog", "Pitch (nm):"))
        self.btnFixDepth.setText(_translate("Dialog", "Fix depth"))
        self.btnSaveMod.setText(_translate("Dialog", "Save modulation patterns"))
        self.btnLoadMod.setText(_translate("Dialog", "Load modulation patterns"))
        self.groupBox_2.setTitle(_translate("Dialog", "ROI Extraction"))
        self.btnExtractROIs.setText(_translate("Dialog", "Extract ROIs using localizations"))
        self.label_34.setText(_translate("Dialog", "Max frames skipped"))
        self.label_35.setText(_translate("Dialog", "Max distance XY (in CRLB)"))
        self.label_37.setText(_translate("Dialog", "Extracted ROIs file:"))
        self.btnBrowseROIs.setText(_translate("Dialog", "Browse"))
        self.label_36.setText(_translate("Dialog", "Max distance intensity (in CRLB)"))
        self.label_38.setText(_translate("Dialog", "Append frames front and end"))
        self.label_39.setText(_translate("Dialog", "Max spot frames:"))
        self.label_40.setText(_translate("Dialog", "Min spot frames:"))
        self.groupBox_3.setTitle(_translate("Dialog", "SIMFLUX Localization (using patterns and extracted ROIs)"))
        self.btnRunSimflux.setText(_translate("Dialog", "SIMFLUX Localization"))
        self.btnDriftCorrection.setText(_translate("Dialog", "Drift correction"))

